server:
  port: 8762
spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
          
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true    
  service-url:
    defaultzone: http://localhost:8761/eureka/
